usermodule/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  #resources :routes
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'routes', to: 'routes#index', as: 'routes'
  get 'details', to: 'routes#show', as: 'details'
  get 'stopdetails', to: 'routes#showstops', as: 'stopdetails'
  get 'showmap', to: 'routes#showmap', as: 'showmap'

  #get '/routes/show/:url' => 'routes#show'

end

usermodule/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

usermodule/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :email, presence: true, uniqueness: true

  before_create { generate_token(:auth_token) }
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

usermodule/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
    #if session[:user_id]
    # @current_user ||= User.find(session[:user_id])
    #else
    #  @current_user = nil
    #end
  end
end

usermodule/app/controllers/home_controller.rb
class HomeController < ApplicationController
 # layout 'standard'
  def index
  end
end

usermodule/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
#  layout 'standard'

  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset
      redirect_to root_url, :notice => "Email sent with password reset instructions."
    else
      redirect_to root_url, :notice => "Email address not found."   
    end  
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(user_params)
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end

  private

   def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

usermodule/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  
  require 'rest-client'
  require 'json'  

  def index
  	search = params[:search]
    url = 'http://178.217.134.14/journeys/api/1/routes'
    response = RestClient.get(url)
    if(search)
      @routes1 = JSON.parse(response.body)
      #@routes['body'].each { |h| h.delete() }
      @routes = @routes1['body'].map { |h| h['name'] == 'Vatiala - Suupantori'; h }
      #@routes1["body"].each do |route|
  	  #	puts route if route["name"] == 'Vatiala - Suupantori'
  	  #end
  	else
  	  @routes = JSON.parse(response.body)
    end
  end	

  def show	
  	url = params[:url]
  	#@url = Route.find(params[:url])
  	response = RestClient.get(url)
    @routes = JSON.parse(response)
  end

  def showstops	
  	url = params[:url]
  	#@url = Route.find(params[:url])
  	response = RestClient.get(url)
    @stops = JSON.parse(response)
  end

  def showmap
  end

end

usermodule/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
#  layout 'standard'
  
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, notice: "Logged out!"
  end
end

usermodule/app/controllers/users_controller.rb
class UsersController < ApplicationController
 # layout 'standard'
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

usermodule/app/helpers/application_helper.rb
module ApplicationHelper
end

usermodule/app/helpers/home_helper.rb
module HomeHelper
end

usermodule/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

usermodule/app/helpers/passwords_helper.rb
module PasswordsHelper
end

usermodule/app/helpers/route_helper.rb
module RouteHelper
end

usermodule/app/helpers/routes_helper.rb
module RoutesHelper
end

usermodule/app/helpers/sessions_helper.rb
module SessionsHelper
end

usermodule/app/helpers/users_helper.rb
module UsersHelper
end

usermodule/app/views/home/index.html.erb
<% if current_user %>
  <p><%= link_to "Edit Profile", edit_user_path(current_user.id) %> </p>
  <p><%= link_to "List Routes", routes_path %> </p>
  <p><%= link_to 'Route Map', :controller => "routes", :action => "showmap" %></p>
<% end %>
 

usermodule/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Usermodule</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyC-D0_T1ha2chW0wY3-WR904o7jwGP15WU"></script>  
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>  
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'> </script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'> </script>

  </head>

  <body>
    <body id = "user">
    <div id = "container" class="container">
      <div id = "header">
        <h1>Welcome</h1>
          <% if current_user %>
            <p>
              <div style="float: right">
              <%= link_to "Log Out", logout_path %>
              </div>
              Logged in as <b><%= current_user.username %> - <%= current_user.email %></b>.
            </p>
          <% else %>
            New users please <%= link_to "Sign Up", signup_path %> or existing users
            <%= link_to "Log In", login_path %> 
          <% end %>
      </div>
      <div class="row">    
        <div id = "content" class="col-lg-12">
          <%= yield -%>
        </div>
      
        <div id = "sidebar"></div>
      </div>
  </body>
</html>

usermodule/app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

  <head>
    <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
    <meta http-equiv = "Content-Language" content = "en-us" />
    <title>Users</title>
  </head>
  
  <body id = "user">
    <div id = "container">
       
      <div id = "header">
        <h1>Welcome</h1>
      </div>
      
      <div id = "content">
        <%= yield -%>
      </div>
      
      <div id = "sidebar"></div>
       
    </div>
  </body>
   
</html>

usermodule/app/views/password_resets/edit.html.erb
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

usermodule/app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

usermodule/app/views/routes/index.html.erb
<% if current_user %>
  
  <table>
  <thead>
    <tr>
      <th>URL</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<div style="float: right"><%= link_to 'Back to Home', :controller => "home", :action => "index" %> </div>
  	<p> <h3> List of Routes </h3> </p>

    <!--<%= form_tag(routes_path, :method => "get") do %>
  	  <div class="field">
    	<%= label_tag :search %>
    	<%= text_field_tag :search, params[:search] %>
  	  </div>
      <div class="actions">
    	<%= submit_tag "Search" %>
  	  </div>
    <% end %> -->

    <% @routes['body'].each do |line| %>
      <tr>
      	<td><%= line['url'] %></td>
        <td><%= line['name'] %></td>
        <td><%= link_to 'Details', :controller => "routes", :action => "show", :url => line['url'] %></td>
      </tr>	
    <% end %>
  </tbody>
</table>
<% end %>

usermodule/app/views/routes/show.html.erb
<% if current_user %>
  
  <table>
  <thead>
    <tr>
      <th>URL</th>
      <th>Arrival Time</th>
      <th>Departure Time</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <div style="float: right"><%= link_to 'Back to Routes', :controller => "routes", :action => "index" %> </div>
    <p> <h3> List of Journeys for '<%= @routes['body'][0]['name'] %>' </h3> </p>
    <% @routes['body'].each do |route| %>
      <% route['journeys'].each do |journey| %>
        <tr>
      	  <td><%= journey['url'] %></td>
          <td><%= journey['arrivalTime'] %></td>
          <td><%= journey['departureTime'] %></td>
          <td><%= link_to 'Stop Details', :controller => "routes", :action => "showstops", :url => journey['url'] %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<% end %>

usermodule/app/views/routes/showmap.html.erb
  <% if current_user %>
    <div style="float: right"><%= link_to 'Back to Home', :controller => "home", :action => "index" %> </div>
    <div style='width: 800px;'>  
      <div id="map-canvas" style='width: 800px; height: 400px;'></div>  
    </div>
  <% end %>  

<script type="text/javascript">
  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'map-canvas'}}, function(){

    var start_point = [61.46546, 23.64219];
    var end_point   = [61.47561, 23.97756];

    var directionsService = new google.maps.DirectionsService();
    var directionsDisplay = new google.maps.DirectionsRenderer();

    directionsDisplay.setMap(handler.getMap());
    var request = {
      origin:      new google.maps.LatLng(start_point[0], start_point[1]),
      destination: new google.maps.LatLng(end_point[0], end_point[1]),
      travelMode:  google.maps.TravelMode.DRIVING
    };

    directionsService.route(request, function(response, status) {
      if (status === google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
      }
    });
  });
</script>


<!-- <script type="text/javascript">  
  handler = Gmaps.build('Google');  
  handler.buildMap({ provider: {}, internal: {id: 'map-canvas'}}, function(){  
    markers = handler.addMarkers([  
      {  
        "lat": 37.3333945,  
        "lng": -121.8806499,  
        "picture": {  
          "width":  32,  
          "height": 32  
        },  
        "infowindow": "SJSU"  
      }  
    ]);  
    handler.bounds.extendWith(markers);  
    handler.fitMapToBounds();  
});  
</script> -->

usermodule/app/views/routes/showstops.html.erb
<% if current_user %>
  
  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Arrival Time</th>
      <th>Departure Time</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
     <div style="float: right"><%= link_to 'Back to Details', :controller => "routes", :action => "show", :url => @stops['body'][0]['routeUrl'] %></div>
     <p> <h3> List of Stops for '<%= @stops['body'][0]['headSign'] %>' </h3> </p>
    <% @stops['body'].each do |stop| %>
      <% stop['calls'].each do |call| %>
        <tr>
      	  <td><%= call['stopPoint']['name'] %></td>
          <td><%= call['arrivalTime'] %></td>
          <td><%= call['departureTime'] %></td>
          <td><%= call['stopPoint']['location'] %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>

</table>
<% end %> 

usermodule/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

usermodule/app/views/users/edit.html.erb
<div style="float: right"><%= link_to 'Back to Home', :controller => "home", :action => "index" %></div>

<h1>Editing User</h1>

<%= render 'form', user: @user %>

usermodule/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, action: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

usermodule/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form', user: @user %>

usermodule/app/views/users/show.html.erb
<div style="float: right"><%= link_to 'Back to Home', :controller => "home", :action => "index" %></div>
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>